import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma, Orbitron } from "next/font/google";
import "./globals.css";
import { Button } from "@heroui/react/button";
import Logo from "./components/ui/Logo";
import { Navbar } from "./components/ui/navbar/Navbar";
import { Heart, Search } from "lucide-react";
import { microgramma } from "./font";
import Footer from "./components/Footer";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400",
});

export const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${michroma.variable} ${orbitron.variable} ${microgramma.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar
          brand={
            <>
              <Logo />
            </>
          }
          items={[
            { label: "Home", href: "/" },
            { label: "Inventory", href: "/inventory", isActive: true },
            { label: "Brand", href: "/brand" },
            { label: "Services", href: "/services" },
            { label: "About Us", href: "/about" },
            { label: "Blog", href: "/blog" },
            { label: "Contact", href: "/contact" },
          ]}
          rightContent={
            <>
              <Search className="text-text hover:text-primary transition-all duration-200 cursor-pointer" />
              <Heart className="text-text hover:text-primary transition-all duration-200 cursor-pointer" />
              <Link
                href="/auth/login"
                className="rounded-md text-text py-1.5 px-3 bg-background border border-border hover:border-primary hover:text-muted transition-all duration-200"
              >
                Login
              </Link>
              <Button className="rounded-md bg-primary hover:bg-primary-hover">
                Book a Test Drive
              </Button>
            </>
          }
        />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
